import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MotionConfig } from "framer-motion";
import { SmoothScroll } from "@/components/providers/smooth-scroll";
import { CustomCursor } from "@/components/cursor/custom-cursor";
import { LoadingScreen } from "@/components/layout/loading-screen";
import { Nav } from "@/components/layout/nav";
import { Footer } from "@/components/layout/footer";
import { siteConfig } from "@/content/seo";
import { socialLinks } from "@/content/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.defaultTitle,
    template: siteConfig.titleTemplate,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,
  // og:image / twitter:image / favicon / apple-touch-icon are generated by
  // the opengraph-image.tsx, icon.tsx and apple-icon.tsx file conventions —
  // don't duplicate them here (a stale static path here previously pointed
  // at a PNG that didn't exist, breaking every link preview).
  openGraph: {
    type: "website",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.defaultTitle,
    description: siteConfig.tagline,
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.defaultTitle,
    description: siteConfig.tagline,
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: siteConfig.themeColor,
  colorScheme: "dark",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable} h-full`}>
      <body className="flex min-h-full flex-col bg-bg antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: siteConfig.name,
              url: siteConfig.url,
              description: siteConfig.description,
              sameAs: socialLinks.map((social) => social.href),
            }),
          }}
        />
        <a
          href="#main-content"
          className="fixed left-4 -top-24 z-[200] rounded-full bg-orange px-5 py-2.5 text-sm font-medium text-black transition-[top] focus:top-4"
        >
          Skip to content
        </a>
        {/* reducedMotion="user" makes every Framer Motion animation on the
            site respect prefers-reduced-motion automatically (collapsing
            transforms to instant, keeping opacity fades). Non-Framer motion
            (the loading bar, cursor, WebGL shader) is handled separately via
            usePrefersReducedMotion in each of those components. */}
        <MotionConfig reducedMotion="user">
          <SmoothScroll>
            <LoadingScreen />
            <CustomCursor />
            <div className="grain" aria-hidden="true" />
            <Nav />
            <main id="main-content" className="flex-1">
              {children}
            </main>
            <Footer />
          </SmoothScroll>
        </MotionConfig>
      </body>
    </html>
  );
}
