import type { Metadata, Viewport } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { MotionConfig } from "framer-motion";
import { AppReadyProvider } from "@/components/providers/app-ready";
import { SmoothScroll } from "@/components/providers/smooth-scroll";
import { CustomCursor } from "@/components/cursor/custom-cursor";
import Loader from "@/components/Loader";
import { Nav } from "@/components/layout/nav";
import { Footer } from "@/components/layout/footer";
import { siteConfig } from "@/content/seo";
import { socialLinks } from "@/content/navigation";
import { ArcMarkSprite } from "@/components/icons/arc-mark";

// No Inter any more — the body/UI face is now Helvetica Neue, a system
// font (see --font-sans in globals.css), so there's nothing to load for
// it. Archivo stays for display headlines only.
const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: "800",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.defaultTitle,
    template: siteConfig.titleTemplate,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: siteConfig.name }],
  creator: siteConfig.name,
  // favicon / apple-touch-icon / og:image / twitter:image point straight at
  // the static files in public/. These used to be generated by icon.tsx,
  // apple-icon.tsx and opengraph-image.tsx route handlers that each called
  // `NextResponse.redirect()` with a relative path — invalid (redirect
  // needs an absolute URL) and fatal under `output: "export"`, since static
  // export has no request/host to resolve a relative URL against. It broke
  // `next build` outright. Pointing metadata at the public/ files directly
  // sidesteps that: no route handler, no redirect, just static assets.
  icons: {
    icon: "/icon.svg",
    apple: "/apple-icon.svg",
  },
  openGraph: {
    type: "website",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.defaultTitle,
    description: siteConfig.tagline,
    images: ["/opengraph.svg"],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.defaultTitle,
    description: siteConfig.tagline,
    images: ["/opengraph.svg"],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export const viewport: Viewport = {
  themeColor: siteConfig.themeColor,
  colorScheme: "dark",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${archivo.variable} h-full`}>
      <body className="flex min-h-full flex-col bg-bg antialiased">
        {/* Defines #arc-mark once so every <use href="#arc-mark"> on the
            page (nav, hero) resolves — see components/icons/arc-mark.tsx. */}
        <ArcMarkSprite />
        {/* One shared provider: Loader calls useSetAppReady() to report
            its own completion outward, Nav and the homepage Hero call
            useAppReady() to time their entrances off that instead of
            their own mount — both need to be inside the SAME provider
            instance, not siblings of it, for the context to actually
            connect them. See app-ready.tsx. */}
        <AppReadyProvider>
          <Loader />
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "Organization",
                name: siteConfig.name,
                url: siteConfig.url,
                description: siteConfig.description,
                sameAs: socialLinks.map((social) => social.href),
              }),
            }}
          />
          <a
            href="#main-content"
            className="fixed left-4 -top-24 z-[200] rounded-full bg-orange px-5 py-2.5 text-sm font-medium text-black transition-[top] focus:top-4"
          >
            Skip to content
          </a>
          {/* reducedMotion="user" makes every Framer Motion animation on the
              site respect prefers-reduced-motion automatically (collapsing
              transforms to instant, keeping opacity fades). Non-Framer motion
              (the cursor, WebGL shader) is handled separately via
              usePrefersReducedMotion in each of those components. Loader
              (above) is the exception — it doesn't check reduced-motion. */}
          <MotionConfig reducedMotion="user">
            <SmoothScroll>
              <CustomCursor />
              <div className="grain" aria-hidden="true" />
              <Nav />
              <main id="main-content" className="flex-1">
                {children}
              </main>
              <Footer />
            </SmoothScroll>
          </MotionConfig>
        </AppReadyProvider>
      </body>
    </html>
  );
}
